<?php

namespace App\Enums;

enum EventType: string
{
    case NEW_ORDER = 'NEW_ORDER';
    case ORDER_EXPIRED = 'ORDER_EXPIRED';
    case SURGE_STARTED = 'SURGE_STARTED';
    case SURGE_ENDED = 'SURGE_ENDED';
    case TRAFFIC_CHANGED = 'TRAFFIC_CHANGED';
    case ROAD_CLOSED = 'ROAD_CLOSED';
    case ROAD_REOPENED = 'ROAD_REOPENED';
    case WEATHER_CHANGED = 'WEATHER_CHANGED';
    case RESTAURANT_DELAY_CHANGED = 'RESTAURANT_DELAY_CHANGED';
    case ORDER_ACCEPTED = 'ORDER_ACCEPTED';
    case PICKUP_COMPLETED = 'PICKUP_COMPLETED';
    case DELIVERY_COMPLETED = 'DELIVERY_COMPLETED';
}
