<?php

namespace App\Enums;

enum ReasonCode: string
{
    case HIGH_HOURLY_RATE = 'HIGH_HOURLY_RATE';
    case HIGH_NET_PROFIT = 'HIGH_NET_PROFIT';
    case SHORT_PICKUP = 'SHORT_PICKUP';
    case LOW_DEADHEAD = 'LOW_DEADHEAD';
    case HIGH_DEMAND_DESTINATION = 'HIGH_DEMAND_DESTINATION';
    case BATCH_COMPATIBLE = 'BATCH_COMPATIBLE';
    case LOW_DELAY_RISK = 'LOW_DELAY_RISK';
    case SURGE_ADVANTAGE = 'SURGE_ADVANTAGE';
    case SHIFT_FIT = 'SHIFT_FIT';
    case LOW_HOURLY_RATE = 'LOW_HOURLY_RATE';
    case LONG_PICKUP = 'LONG_PICKUP';
    case LOW_DEMAND_DESTINATION = 'LOW_DEMAND_DESTINATION';
    case HIGH_DELAY_RISK = 'HIGH_DELAY_RISK';
    case TRAFFIC_PENALTY = 'TRAFFIC_PENALTY';
    case ROAD_CLOSURE = 'ROAD_CLOSURE';
    case SHIFT_TOO_SHORT = 'SHIFT_TOO_SHORT';
    case INCOMPATIBLE_BATCH = 'INCOMPATIBLE_BATCH';
}
